{% set version = "1.2-5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spacetime
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spacetime_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spacetime/spacetime_{{ version }}.tar.gz
  sha256: 8f2acc3886780a902fb0476d6ab271e6640be1a1af4c7f9a21d8a2882fb72746

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-intervals
    - r-lattice
    - r-sp >=1.1_0
    - r-xts >=0.8_8
    - r-zoo >=1.7_9
  run:
    - r-base
    - r-intervals
    - r-lattice
    - r-sp >=1.1_0
    - r-xts >=0.8_8
    - r-zoo >=1.7_9

test:
  commands:
    - $R -e "library('spacetime')"           # [not win]
    - "\"%R%\" -e \"library('spacetime')\""  # [win]

about:
  home: http://github.com/edzer/spacetime
  license: GPL-2.0-or-later
  summary: Classes and methods for spatio-temporal data, including space-time regular lattices, sparse lattices, irregular data, and trajectories; utility functions for plotting data as map sequences (lattice or animation) or multiple time series; methods for spatial and temporal selection and subsetting, as well as for
    spatial/temporal/spatio-temporal matching or aggregation, retrieving coordinates, print, summary, etc.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jsignell
