appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: j3KVcPGMuDmiZicacYVCC6B+3n3zVz60evRIk3fb9tScfFVEeHMzG3EaV9Efnllupz30thn4zeZTg81T101/Wcwbv3G0uDiekBujHlrZ8F2GdQF15ddzGAOtGj059Y8ZNfElxhlQt4V6RdNrWLsDzlb+JQu6D1wRD+rcfLUAadKw/po7GN6z8Q/BePL1x8nd6TTrtnpBFGKzZMZVKkfQm4znqIQaASUjLEHHAvz/pMgbVz2jMqNSXbiCZLGabp2ZB5q+l09WDIXHN6px2KmRC1AHLBmDbMBMvml4hJcI/QhFz6DhaOlW8PUAQsfXuJCq6xctCdaOkdRpwSUdgRk7PFuS4tJbtRZ4NbjMzFSQu4ptolZuQQ3+zvSaShdNWGo84jHSe+83pWJN02/2l3LHIu7y0qGWE2TCOxOT3CHeU7sWJgFurFjw9OdTBT/wcnJB9ac25IXKB7DZBhsk3hNycRs480uUHOdoMIK7IsTePo0hm49zhYsqoBdm8aRNH1QNptiKzn+LnPn+RFn3+ToyQyig8w0jn9+pUdAP5Zh7V/Mqs5VvI1tLCTAv7endhIiWQW1Xuji7OE5cq96NfPiDsXBZGEtJ0lgSzFSYwsDyv7aWOVsp6IG8kKR6ybUPf7Cgc6ot0a1JrmvRWlwmLt7OvGBgOUa3ja6W6XEaFlGN61g=
conda_forge_output_validation: false
